# Generated by Django 4.2.7 on 2025-06-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название товара')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('discount_price', models.FloatField(verbose_name='Цена со скидкой')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('reviews_count', models.IntegerField(verbose_name='Количество отзывов')),
                ('category', models.CharField(max_length=200, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
